### intervals are specified in milliseconds

chain_id = 80094

## EL config
distributor = "0xD2f19a79b026Fb636A7c300bF5947df113940761"
block_poll_interval = 100

## CL proof config
beacon_poll_interval = 50
beacon_max_retries = 12

fallback_wait_interval = 30000 ## only applicable when fallback-mode is enabled
